gui:
  showCommandLog: false
  border: single 
  nerdFontsVersion: 2
  showNumstatInFilesView: true

git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --syntax-theme Dracula --side-by-side

