gui:
  showCommandLog: false
  border: single 
  nerdFontsVersion: 2
  showNumstatInFilesView: true
  sidePanelWidth: 0.2
 
git:
  pagers:
    - colorArg: always
      pager: ~/.config/lazygit/delta-pager.sh
